"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class classification_t(object):
    __slots__ = ["category", "name", "confidence"]

    def __init__(self):
        self.category = ""
        self.name = ""
        self.confidence = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(classification_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __category_encoded = self.category.encode('utf-8')
        buf.write(struct.pack('>I', len(__category_encoded)+1))
        buf.write(__category_encoded)
        buf.write(b"\0")
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">d", self.confidence))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != classification_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return classification_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = classification_t()
        __category_len = struct.unpack('>I', buf.read(4))[0]
        self.category = buf.read(__category_len)[:-1].decode('utf-8', 'replace')
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.confidence = struct.unpack(">d", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if classification_t in parents: return 0
        tmphash = (0x139c236a7ed87265) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if classification_t._packed_fingerprint is None:
            classification_t._packed_fingerprint = struct.pack(">Q", classification_t._get_hash_recursive([]))
        return classification_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

