"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mobilesim.lcmtypes.control_law_status_t

class control_law_status_list_t(object):
    __slots__ = ["utime", "nstatuses", "statuses"]

    def __init__(self):
        self.utime = 0
        self.nstatuses = 0
        self.statuses = []

    def encode(self):
        buf = BytesIO()
        buf.write(control_law_status_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.nstatuses))
        for i0 in range(self.nstatuses):
            assert self.statuses[i0]._get_packed_fingerprint() == mobilesim.lcmtypes.control_law_status_t._get_packed_fingerprint()
            self.statuses[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_law_status_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_law_status_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_law_status_list_t()
        self.utime, self.nstatuses = struct.unpack(">qi", buf.read(12))
        self.statuses = []
        for i0 in range(self.nstatuses):
            self.statuses.append(mobilesim.lcmtypes.control_law_status_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_law_status_list_t in parents: return 0
        newparents = parents + [control_law_status_list_t]
        tmphash = (0xa72017a5b044fc76+ mobilesim.lcmtypes.control_law_status_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_law_status_list_t._packed_fingerprint is None:
            control_law_status_list_t._packed_fingerprint = struct.pack(">Q", control_law_status_list_t._get_hash_recursive([]))
        return control_law_status_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

