"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mobilesim.lcmtypes.typed_value_t

import mobilesim.lcmtypes.condition_test_t

class control_law_t(object):
    __slots__ = ["utime", "name", "id", "num_params", "param_names", "param_values", "termination_condition"]

    def __init__(self):
        self.utime = 0
        self.name = ""
        self.id = 0
        self.num_params = 0
        self.param_names = []
        self.param_values = []
        self.termination_condition = mobilesim.lcmtypes.condition_test_t()

    def encode(self):
        buf = BytesIO()
        buf.write(control_law_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">ii", self.id, self.num_params))
        for i0 in range(self.num_params):
            __param_names_encoded = self.param_names[i0].encode('utf-8')
            buf.write(struct.pack('>I', len(__param_names_encoded)+1))
            buf.write(__param_names_encoded)
            buf.write(b"\0")
        for i0 in range(self.num_params):
            assert self.param_values[i0]._get_packed_fingerprint() == mobilesim.lcmtypes.typed_value_t._get_packed_fingerprint()
            self.param_values[i0]._encode_one(buf)
        assert self.termination_condition._get_packed_fingerprint() == mobilesim.lcmtypes.condition_test_t._get_packed_fingerprint()
        self.termination_condition._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_law_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_law_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_law_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.id, self.num_params = struct.unpack(">ii", buf.read(8))
        self.param_names = []
        for i0 in range(self.num_params):
            __param_names_len = struct.unpack('>I', buf.read(4))[0]
            self.param_names.append(buf.read(__param_names_len)[:-1].decode('utf-8', 'replace'))
        self.param_values = []
        for i0 in range(self.num_params):
            self.param_values.append(mobilesim.lcmtypes.typed_value_t._decode_one(buf))
        self.termination_condition = mobilesim.lcmtypes.condition_test_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_law_t in parents: return 0
        newparents = parents + [control_law_t]
        tmphash = (0x944d24f9e21c17a6+ mobilesim.lcmtypes.typed_value_t._get_hash_recursive(newparents)+ mobilesim.lcmtypes.condition_test_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_law_t._packed_fingerprint is None:
            control_law_t._packed_fingerprint = struct.pack(">Q", control_law_t._get_hash_recursive([]))
        return control_law_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

