"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class control_law_status_t(object):
    __slots__ = ["utime", "id", "name", "status"]

    def __init__(self):
        self.utime = 0
        self.id = 0
        self.name = ""
        self.status = ""

    def encode(self):
        buf = BytesIO()
        buf.write(control_law_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.id))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        __status_encoded = self.status.encode('utf-8')
        buf.write(struct.pack('>I', len(__status_encoded)+1))
        buf.write(__status_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != control_law_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return control_law_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = control_law_status_t()
        self.utime, self.id = struct.unpack(">qi", buf.read(12))
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        __status_len = struct.unpack('>I', buf.read(4))[0]
        self.status = buf.read(__status_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if control_law_status_t in parents: return 0
        tmphash = (0x333efa05462635db) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if control_law_status_t._packed_fingerprint is None:
            control_law_status_t._packed_fingerprint = struct.pack(">Q", control_law_status_t._get_hash_recursive([]))
        return control_law_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

