"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class diff_drive_t(object):
    __slots__ = ["utime", "left", "left_enabled", "right", "right_enabled"]

    def __init__(self):
        self.utime = 0
        self.left = 0.0
        self.left_enabled = False
        self.right = 0.0
        self.right_enabled = False

    def encode(self):
        buf = BytesIO()
        buf.write(diff_drive_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdbdb", self.utime, self.left, self.left_enabled, self.right, self.right_enabled))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != diff_drive_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return diff_drive_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = diff_drive_t()
        self.utime, self.left = struct.unpack(">qd", buf.read(16))
        self.left_enabled = bool(struct.unpack('b', buf.read(1))[0])
        self.right = struct.unpack(">d", buf.read(8))[0]
        self.right_enabled = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if diff_drive_t in parents: return 0
        tmphash = (0x2ab615ed58b54790) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if diff_drive_t._packed_fingerprint is None:
            diff_drive_t._packed_fingerprint = struct.pack(">Q", diff_drive_t._get_hash_recursive([]))
        return diff_drive_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

