"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class interaction_message_t(object):
    __slots__ = ["utime", "message_id", "message_type", "message"]

    def __init__(self):
        self.utime = 0
        self.message_id = 0
        self.message_type = ""
        self.message = ""

    def encode(self):
        buf = BytesIO()
        buf.write(interaction_message_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.message_id))
        __message_type_encoded = self.message_type.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_type_encoded)+1))
        buf.write(__message_type_encoded)
        buf.write(b"\0")
        __message_encoded = self.message.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_encoded)+1))
        buf.write(__message_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != interaction_message_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return interaction_message_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = interaction_message_t()
        self.utime, self.message_id = struct.unpack(">qi", buf.read(12))
        __message_type_len = struct.unpack('>I', buf.read(4))[0]
        self.message_type = buf.read(__message_type_len)[:-1].decode('utf-8', 'replace')
        __message_len = struct.unpack('>I', buf.read(4))[0]
        self.message = buf.read(__message_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if interaction_message_t in parents: return 0
        tmphash = (0x47edac78525f763d) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if interaction_message_t._packed_fingerprint is None:
            interaction_message_t._packed_fingerprint = struct.pack(">Q", interaction_message_t._get_hash_recursive([]))
        return interaction_message_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

