"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcmdoubles_t(object):
    __slots__ = ["utime", "ndata", "data"]

    def __init__(self):
        self.utime = 0
        self.ndata = 0
        self.data = []

    def encode(self):
        buf = BytesIO()
        buf.write(lcmdoubles_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.ndata))
        buf.write(struct.pack('>%dd' % self.ndata, *self.data[:self.ndata]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmdoubles_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmdoubles_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcmdoubles_t()
        self.utime, self.ndata = struct.unpack(">qi", buf.read(12))
        self.data = struct.unpack('>%dd' % self.ndata, buf.read(self.ndata * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if lcmdoubles_t in parents: return 0
        tmphash = (0x791ce425d5fed94) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcmdoubles_t._packed_fingerprint is None:
            lcmdoubles_t._packed_fingerprint = struct.pack(">Q", lcmdoubles_t._get_hash_recursive([]))
        return lcmdoubles_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

