"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mobilesim.lcmtypes.object_data_t

class object_data_list_t(object):
    __slots__ = ["utime", "num_objects", "objects"]

    def __init__(self):
        self.utime = 0
        self.num_objects = 0
        self.objects = []

    def encode(self):
        buf = BytesIO()
        buf.write(object_data_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.num_objects))
        for i0 in range(self.num_objects):
            assert self.objects[i0]._get_packed_fingerprint() == mobilesim.lcmtypes.object_data_t._get_packed_fingerprint()
            self.objects[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != object_data_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return object_data_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = object_data_list_t()
        self.utime, self.num_objects = struct.unpack(">qi", buf.read(12))
        self.objects = []
        for i0 in range(self.num_objects):
            self.objects.append(mobilesim.lcmtypes.object_data_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if object_data_list_t in parents: return 0
        newparents = parents + [object_data_list_t]
        tmphash = (0x92af6330dbe6ff69+ mobilesim.lcmtypes.object_data_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if object_data_list_t._packed_fingerprint is None:
            object_data_list_t._packed_fingerprint = struct.pack(">Q", object_data_list_t._get_hash_recursive([]))
        return object_data_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

