"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mobilesim.lcmtypes.classification_t

class object_data_t(object):
    __slots__ = ["utime", "id", "xyzrpy", "lenxyz", "num_classifications", "classifications"]

    def __init__(self):
        self.utime = 0
        self.id = 0
        self.xyzrpy = [ 0.0 for dim0 in range(6) ]
        self.lenxyz = [ 0.0 for dim0 in range(3) ]
        self.num_classifications = 0
        self.classifications = []

    def encode(self):
        buf = BytesIO()
        buf.write(object_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.id))
        buf.write(struct.pack('>6d', *self.xyzrpy[:6]))
        buf.write(struct.pack('>3d', *self.lenxyz[:3]))
        buf.write(struct.pack(">i", self.num_classifications))
        for i0 in range(self.num_classifications):
            assert self.classifications[i0]._get_packed_fingerprint() == mobilesim.lcmtypes.classification_t._get_packed_fingerprint()
            self.classifications[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != object_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return object_data_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = object_data_t()
        self.utime, self.id = struct.unpack(">qi", buf.read(12))
        self.xyzrpy = struct.unpack('>6d', buf.read(48))
        self.lenxyz = struct.unpack('>3d', buf.read(24))
        self.num_classifications = struct.unpack(">i", buf.read(4))[0]
        self.classifications = []
        for i0 in range(self.num_classifications):
            self.classifications.append(mobilesim.lcmtypes.classification_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if object_data_t in parents: return 0
        newparents = parents + [object_data_t]
        tmphash = (0x919feaadea864364+ mobilesim.lcmtypes.classification_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if object_data_t._packed_fingerprint is None:
            object_data_t._packed_fingerprint = struct.pack(">Q", object_data_t._get_hash_recursive([]))
        return object_data_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

