"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_task_t(object):
    __slots__ = ["task", "repeat"]

    FREEZE = 0
    WAITING = 1
    GOTO_LATLON = 2
    GOTO_GLOBAL = 3
    COMM_RELAY = 5

    def __init__(self):
        self.task = 0
        self.repeat = 0

    def encode(self):
        buf = BytesIO()
        buf.write(robot_task_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bb", self.task, self.repeat))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_task_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_task_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_task_t()
        self.task, self.repeat = struct.unpack(">bb", buf.read(2))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_task_t in parents: return 0
        tmphash = (0x381954300d50d8a9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_task_t._packed_fingerprint is None:
            robot_task_t._packed_fingerprint = struct.pack(">Q", robot_task_t._get_hash_recursive([]))
        return robot_task_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

