"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class robot_info_t(object):
    __slots__ = ["utime", "current_waypoint", "xyzrpy", "held_object"]

    def __init__(self):
        self.utime = 0
        self.current_waypoint = ""
        self.xyzrpy = [ 0.0 for dim0 in range(6) ]
        self.held_object = 0

    def encode(self):
        buf = BytesIO()
        buf.write(robot_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __current_waypoint_encoded = self.current_waypoint.encode('utf-8')
        buf.write(struct.pack('>I', len(__current_waypoint_encoded)+1))
        buf.write(__current_waypoint_encoded)
        buf.write(b"\0")
        buf.write(struct.pack('>6d', *self.xyzrpy[:6]))
        buf.write(struct.pack(">i", self.held_object))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_info_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __current_waypoint_len = struct.unpack('>I', buf.read(4))[0]
        self.current_waypoint = buf.read(__current_waypoint_len)[:-1].decode('utf-8', 'replace')
        self.xyzrpy = struct.unpack('>6d', buf.read(48))
        self.held_object = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_info_t in parents: return 0
        tmphash = (0x5d2d45e0a0b000ae) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_info_t._packed_fingerprint is None:
            robot_info_t._packed_fingerprint = struct.pack(">Q", robot_info_t._get_hash_recursive([]))
        return robot_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

