"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import mobilesim.lcmtypes.grid_map_t

class robot_map_data_t(object):
    __slots__ = ["utime", "gridmap", "latlon_deg", "xyt_local"]

    def __init__(self):
        self.utime = 0
        self.gridmap = mobilesim.lcmtypes.grid_map_t()
        self.latlon_deg = [ 0.0 for dim0 in range(2) ]
        self.xyt_local = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(robot_map_data_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.gridmap._get_packed_fingerprint() == mobilesim.lcmtypes.grid_map_t._get_packed_fingerprint()
        self.gridmap._encode_one(buf)
        buf.write(struct.pack('>2d', *self.latlon_deg[:2]))
        buf.write(struct.pack('>3d', *self.xyt_local[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != robot_map_data_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return robot_map_data_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = robot_map_data_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.gridmap = mobilesim.lcmtypes.grid_map_t._decode_one(buf)
        self.latlon_deg = struct.unpack('>2d', buf.read(16))
        self.xyt_local = struct.unpack('>3d', buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if robot_map_data_t in parents: return 0
        newparents = parents + [robot_map_data_t]
        tmphash = (0xaded8231ac1b19ee+ mobilesim.lcmtypes.grid_map_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if robot_map_data_t._packed_fingerprint is None:
            robot_map_data_t._packed_fingerprint = struct.pack(">Q", robot_map_data_t._get_hash_recursive([]))
        return robot_map_data_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

