"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class speak_t(object):
    __slots__ = ["utime", "args", "priority", "message"]

    def __init__(self):
        self.utime = 0
        self.args = ""
        self.priority = 0
        self.message = ""

    def encode(self):
        buf = BytesIO()
        buf.write(speak_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __args_encoded = self.args.encode('utf-8')
        buf.write(struct.pack('>I', len(__args_encoded)+1))
        buf.write(__args_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.priority))
        __message_encoded = self.message.encode('utf-8')
        buf.write(struct.pack('>I', len(__message_encoded)+1))
        buf.write(__message_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != speak_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return speak_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = speak_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __args_len = struct.unpack('>I', buf.read(4))[0]
        self.args = buf.read(__args_len)[:-1].decode('utf-8', 'replace')
        self.priority = struct.unpack(">i", buf.read(4))[0]
        __message_len = struct.unpack('>I', buf.read(4))[0]
        self.message = buf.read(__message_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if speak_t in parents: return 0
        tmphash = (0x2f999858d6246eb9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if speak_t._packed_fingerprint is None:
            speak_t._packed_fingerprint = struct.pack(">Q", speak_t._get_hash_recursive([]))
        return speak_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

