"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tag_classification_t(object):
    __slots__ = ["utime", "name", "tag_id", "xyzrpy", "confidence", "range"]

    def __init__(self):
        self.utime = 0
        self.name = ""
        self.tag_id = 0
        self.xyzrpy = [ 0.0 for dim0 in range(6) ]
        self.confidence = 0.0
        self.range = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(tag_classification_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.tag_id))
        buf.write(struct.pack('>6d', *self.xyzrpy[:6]))
        buf.write(struct.pack(">dd", self.confidence, self.range))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tag_classification_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tag_classification_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tag_classification_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.tag_id = struct.unpack(">i", buf.read(4))[0]
        self.xyzrpy = struct.unpack('>6d', buf.read(48))
        self.confidence, self.range = struct.unpack(">dd", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tag_classification_t in parents: return 0
        tmphash = (0x84c17cf55b72475a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tag_classification_t._packed_fingerprint is None:
            tag_classification_t._packed_fingerprint = struct.pack(">Q", tag_classification_t._get_hash_recursive([]))
        return tag_classification_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

