/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package probcog.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class category_t implements lcm.lcm.LCMEncodable
{
    public int cat;
 
    public category_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xd21b6439f9225c57L;
 
    public static final int CAT_COLOR = 1;
    public static final int CAT_SHAPE = 2;
    public static final int CAT_SIZE = 3;
    public static final int CAT_LOCATION = 4;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(probcog.lcmtypes.category_t.class))
            return 0L;
 
        classes.add(probcog.lcmtypes.category_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeInt(this.cat); 
 
    }
 
    public category_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public category_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static probcog.lcmtypes.category_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        probcog.lcmtypes.category_t o = new probcog.lcmtypes.category_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.cat = ins.readInt();
 
    }
 
    public probcog.lcmtypes.category_t copy()
    {
        probcog.lcmtypes.category_t outobj = new probcog.lcmtypes.category_t();
        outobj.cat = this.cat;
 
        return outobj;
    }
 
}

