/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package probcog.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class kinect_status_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int rgblen;
    public int depthlen;
    public byte rgb[];
    public byte depth[];
    public double dx;
    public double dy;
    public double dz;
 
    public kinect_status_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x5483defaa662e03fL;
 
    public static final int WIDTH = 640;
    public static final int HEIGHT = 480;

    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(probcog.lcmtypes.kinect_status_t.class))
            return 0L;
 
        classes.add(probcog.lcmtypes.kinect_status_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.rgblen); 
 
        outs.writeInt(this.depthlen); 
 
        if (this.rgblen > 0)
            outs.write(this.rgb, 0, rgblen);
 
        if (this.depthlen > 0)
            outs.write(this.depth, 0, depthlen);
 
        outs.writeDouble(this.dx); 
 
        outs.writeDouble(this.dy); 
 
        outs.writeDouble(this.dz); 
 
    }
 
    public kinect_status_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public kinect_status_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static probcog.lcmtypes.kinect_status_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        probcog.lcmtypes.kinect_status_t o = new probcog.lcmtypes.kinect_status_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.rgblen = ins.readInt();
 
        this.depthlen = ins.readInt();
 
        this.rgb = new byte[(int) rgblen];
        ins.readFully(this.rgb, 0, rgblen); 
        this.depth = new byte[(int) depthlen];
        ins.readFully(this.depth, 0, depthlen); 
        this.dx = ins.readDouble();
 
        this.dy = ins.readDouble();
 
        this.dz = ins.readDouble();
 
    }
 
    public probcog.lcmtypes.kinect_status_t copy()
    {
        probcog.lcmtypes.kinect_status_t outobj = new probcog.lcmtypes.kinect_status_t();
        outobj.utime = this.utime;
 
        outobj.rgblen = this.rgblen;
 
        outobj.depthlen = this.depthlen;
 
        outobj.rgb = new byte[(int) rgblen];
        if (this.rgblen > 0)
            System.arraycopy(this.rgb, 0, outobj.rgb, 0, this.rgblen); 
        outobj.depth = new byte[(int) depthlen];
        if (this.depthlen > 0)
            System.arraycopy(this.depth, 0, outobj.depth, 0, this.depthlen); 
        outobj.dx = this.dx;
 
        outobj.dy = this.dy;
 
        outobj.dz = this.dz;
 
        return outobj;
    }
 
}

