/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package probcog.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class robot_action_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String action;
    public int obj_id;
    public double xyz[];
    public double drop[];
 
    public robot_action_t()
    {
        xyz = new double[3];
        drop = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x6d3466296cacd157L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(probcog.lcmtypes.robot_action_t.class))
            return 0L;
 
        classes.add(probcog.lcmtypes.robot_action_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.action.length()]; this.action.getChars(0, this.action.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.obj_id); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.xyz[a]); 
        }
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.drop[a]); 
        }
 
    }
 
    public robot_action_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public robot_action_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static probcog.lcmtypes.robot_action_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        probcog.lcmtypes.robot_action_t o = new probcog.lcmtypes.robot_action_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.action = new String(__strbuf);
 
        this.obj_id = ins.readInt();
 
        this.xyz = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.xyz[a] = ins.readDouble();
        }
 
        this.drop = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.drop[a] = ins.readDouble();
        }
 
    }
 
    public probcog.lcmtypes.robot_action_t copy()
    {
        probcog.lcmtypes.robot_action_t outobj = new probcog.lcmtypes.robot_action_t();
        outobj.utime = this.utime;
 
        outobj.action = this.action;
 
        outobj.obj_id = this.obj_id;
 
        outobj.xyz = new double[(int) 3];
        System.arraycopy(this.xyz, 0, outobj.xyz, 0, 3); 
        outobj.drop = new double[(int) 3];
        System.arraycopy(this.drop, 0, outobj.drop, 0, 3); 
        return outobj;
    }
 
}

