/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package soargroup.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class control_law_status_list_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public int nstatuses;
    public soargroup.rosie.lcmtypes.control_law_status_t statuses[];
 
    public control_law_status_list_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xa72017a5b044fc76L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(soargroup.rosie.lcmtypes.control_law_status_list_t.class))
            return 0L;
 
        classes.add(soargroup.rosie.lcmtypes.control_law_status_list_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + soargroup.rosie.lcmtypes.control_law_status_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeInt(this.nstatuses); 
 
        for (int a = 0; a < this.nstatuses; a++) {
            this.statuses[a]._encodeRecursive(outs); 
        }
 
    }
 
    public control_law_status_list_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public control_law_status_list_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static soargroup.rosie.lcmtypes.control_law_status_list_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        soargroup.rosie.lcmtypes.control_law_status_list_t o = new soargroup.rosie.lcmtypes.control_law_status_list_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.nstatuses = ins.readInt();
 
        this.statuses = new soargroup.rosie.lcmtypes.control_law_status_t[(int) nstatuses];
        for (int a = 0; a < this.nstatuses; a++) {
            this.statuses[a] = soargroup.rosie.lcmtypes.control_law_status_t._decodeRecursiveFactory(ins);
        }
 
    }
 
    public soargroup.rosie.lcmtypes.control_law_status_list_t copy()
    {
        soargroup.rosie.lcmtypes.control_law_status_list_t outobj = new soargroup.rosie.lcmtypes.control_law_status_list_t();
        outobj.utime = this.utime;
 
        outobj.nstatuses = this.nstatuses;
 
        outobj.statuses = new soargroup.rosie.lcmtypes.control_law_status_t[(int) nstatuses];
        for (int a = 0; a < this.nstatuses; a++) {
            outobj.statuses[a] = this.statuses[a].copy();
        }
 
        return outobj;
    }
 
}

