/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package soargroup.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class plan_request_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public byte id;
    public double goalXYT[];
 
    public plan_request_t()
    {
        goalXYT = new double[3];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x57eae2c8454c9953L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(soargroup.rosie.lcmtypes.plan_request_t.class))
            return 0L;
 
        classes.add(soargroup.rosie.lcmtypes.plan_request_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.utime); 
 
        outs.writeByte(this.id); 
 
        for (int a = 0; a < 3; a++) {
            outs.writeDouble(this.goalXYT[a]); 
        }
 
    }
 
    public plan_request_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public plan_request_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static soargroup.rosie.lcmtypes.plan_request_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        soargroup.rosie.lcmtypes.plan_request_t o = new soargroup.rosie.lcmtypes.plan_request_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.utime = ins.readLong();
 
        this.id = ins.readByte();
 
        this.goalXYT = new double[(int) 3];
        for (int a = 0; a < 3; a++) {
            this.goalXYT[a] = ins.readDouble();
        }
 
    }
 
    public soargroup.rosie.lcmtypes.plan_request_t copy()
    {
        soargroup.rosie.lcmtypes.plan_request_t outobj = new soargroup.rosie.lcmtypes.plan_request_t();
        outobj.utime = this.utime;
 
        outobj.id = this.id;
 
        outobj.goalXYT = new double[(int) 3];
        System.arraycopy(this.goalXYT, 0, outobj.goalXYT, 0, 3); 
        return outobj;
    }
 
}

