/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package soargroup.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class rosie_command_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String parameter[];
    public String parameter_name[];
    public String parameter_type[];
    public String name;
 
    public rosie_command_t()
    {
        parameter = new String[6];
        parameter_name = new String[6];
        parameter_type = new String[6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xcc8ce951f45bc381L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(soargroup.rosie.lcmtypes.rosie_command_t.class))
            return 0L;
 
        classes.add(soargroup.rosie.lcmtypes.rosie_command_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[this.parameter[a].length()]; this.parameter[a].getChars(0, this.parameter[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[this.parameter_name[a].length()]; this.parameter_name[a].getChars(0, this.parameter_name[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[this.parameter_type[a].length()]; this.parameter_type[a].getChars(0, this.parameter_type[a].length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
        }
 
        __strbuf = new char[this.name.length()]; this.name.getChars(0, this.name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
    }
 
    public rosie_command_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public rosie_command_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static soargroup.rosie.lcmtypes.rosie_command_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        soargroup.rosie.lcmtypes.rosie_command_t o = new soargroup.rosie.lcmtypes.rosie_command_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        this.parameter = new String[(int) 6];
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.parameter[a] = new String(__strbuf);
        }
 
        this.parameter_name = new String[(int) 6];
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.parameter_name[a] = new String(__strbuf);
        }
 
        this.parameter_type = new String[(int) 6];
        for (int a = 0; a < 6; a++) {
            __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.parameter_type[a] = new String(__strbuf);
        }
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.name = new String(__strbuf);
 
    }
 
    public soargroup.rosie.lcmtypes.rosie_command_t copy()
    {
        soargroup.rosie.lcmtypes.rosie_command_t outobj = new soargroup.rosie.lcmtypes.rosie_command_t();
        outobj.utime = this.utime;
 
        outobj.parameter = new String[(int) 6];
        System.arraycopy(this.parameter, 0, outobj.parameter, 0, 6); 
        outobj.parameter_name = new String[(int) 6];
        System.arraycopy(this.parameter_name, 0, outobj.parameter_name, 0, 6); 
        outobj.parameter_type = new String[(int) 6];
        System.arraycopy(this.parameter_type, 0, outobj.parameter_type, 0, 6); 
        outobj.name = this.name;
 
        return outobj;
    }
 
}

