/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package soargroup.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class tag_classification_t implements lcm.lcm.LCMEncodable
{
    public long utime;
    public String name;
    public int tag_id;
    public double xyzrpy[];
    public double confidence;
    public double range;
 
    public tag_classification_t()
    {
        xyzrpy = new double[6];
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x84c17cf55b72475aL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(soargroup.rosie.lcmtypes.tag_classification_t.class))
            return 0L;
 
        classes.add(soargroup.rosie.lcmtypes.tag_classification_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeLong(this.utime); 
 
        __strbuf = new char[this.name.length()]; this.name.getChars(0, this.name.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        outs.writeInt(this.tag_id); 
 
        for (int a = 0; a < 6; a++) {
            outs.writeDouble(this.xyzrpy[a]); 
        }
 
        outs.writeDouble(this.confidence); 
 
        outs.writeDouble(this.range); 
 
    }
 
    public tag_classification_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public tag_classification_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static soargroup.rosie.lcmtypes.tag_classification_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        soargroup.rosie.lcmtypes.tag_classification_t o = new soargroup.rosie.lcmtypes.tag_classification_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.utime = ins.readLong();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.name = new String(__strbuf);
 
        this.tag_id = ins.readInt();
 
        this.xyzrpy = new double[(int) 6];
        for (int a = 0; a < 6; a++) {
            this.xyzrpy[a] = ins.readDouble();
        }
 
        this.confidence = ins.readDouble();
 
        this.range = ins.readDouble();
 
    }
 
    public soargroup.rosie.lcmtypes.tag_classification_t copy()
    {
        soargroup.rosie.lcmtypes.tag_classification_t outobj = new soargroup.rosie.lcmtypes.tag_classification_t();
        outobj.utime = this.utime;
 
        outobj.name = this.name;
 
        outobj.tag_id = this.tag_id;
 
        outobj.xyzrpy = new double[(int) 6];
        System.arraycopy(this.xyzrpy, 0, outobj.xyzrpy, 0, 6); 
        outobj.confidence = this.confidence;
 
        outobj.range = this.range;
 
        return outobj;
    }
 
}

