/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package soargroup.rosie.lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class training_label_t implements lcm.lcm.LCMEncodable
{
    public int id;
    public String label;
    public soargroup.rosie.lcmtypes.category_t cat;
 
    public training_label_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xbfbf5ffa86c59cb3L;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(soargroup.rosie.lcmtypes.training_label_t.class))
            return 0L;
 
        classes.add(soargroup.rosie.lcmtypes.training_label_t.class);
        long hash = LCM_FINGERPRINT_BASE
             + soargroup.rosie.lcmtypes.category_t._hashRecursive(classes)
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        char[] __strbuf = null;
        outs.writeInt(this.id); 
 
        __strbuf = new char[this.label.length()]; this.label.getChars(0, this.label.length(), __strbuf, 0); outs.writeInt(__strbuf.length+1); for (int _i = 0; _i < __strbuf.length; _i++) outs.write(__strbuf[_i]); outs.writeByte(0); 
 
        this.cat._encodeRecursive(outs); 
 
    }
 
    public training_label_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public training_label_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static soargroup.rosie.lcmtypes.training_label_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        soargroup.rosie.lcmtypes.training_label_t o = new soargroup.rosie.lcmtypes.training_label_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        char[] __strbuf = null;
        this.id = ins.readInt();
 
        __strbuf = new char[ins.readInt()-1]; for (int _i = 0; _i < __strbuf.length; _i++) __strbuf[_i] = (char) (ins.readByte()&0xff); ins.readByte(); this.label = new String(__strbuf);
 
        this.cat = soargroup.rosie.lcmtypes.category_t._decodeRecursiveFactory(ins);
 
    }
 
    public soargroup.rosie.lcmtypes.training_label_t copy()
    {
        soargroup.rosie.lcmtypes.training_label_t outobj = new soargroup.rosie.lcmtypes.training_label_t();
        outobj.id = this.id;
 
        outobj.label = this.label;
 
        outobj.cat = this.cat.copy();
 
        return outobj;
    }
 
}

