LCM = lcm-gen

LCMTYPES_NAMES := $(shell cd ../lcmtypes && ls *.lcm)

# Construct the pathnames to the java types.
LCMTYPES_JAVA := $(LCMTYPES_NAMES:%.lcm=%.java)
LCMTYPES_JAVA := $(addprefix src/probcog/lcmtypes/,$(LCMTYPES_JAVA))

SUFFIXES += .java .lcm

all: $(LCMTYPES_JAVA)


src/probcog/lcmtypes/%.java: ../lcmtypes/%.lcm
	$(LCM) -j  --jpath=src --jdefaultpkg=probcog.lcmtypes $<

clean:
	rm -rf *~ src/probcog/lcmtypes/*
